# Generated by Django 4.1.7 on 2023-03-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredientes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("calorias", models.DecimalField(decimal_places=2, max_digits=5)),
                ("proteina", models.DecimalField(decimal_places=2, max_digits=5)),
                ("gordura", models.DecimalField(decimal_places=2, max_digits=5)),
                ("carboidrato", models.DecimalField(decimal_places=2, max_digits=5)),
                ("vegetal", models.BooleanField(default=False)),
            ],
        ),
    ]
