# Generated by Django 4.1.7 on 2023-03-13 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_remove_ingredientes_calorias"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tempo_preparacao", models.IntegerField()),
                ("porcao", models.IntegerField()),
                ("alcoolico", models.BooleanField(default=False)),
                (
                    "item_media_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="menu.itemmedia"
                    ),
                ),
            ],
        ),
    ]
