# Generated by Django 4.1.7 on 2023-03-13 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0005_alter_item_item_media_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_media_id",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.itemmedia",
            ),
        ),
    ]
