# Generated by Django 4.1.7 on 2023-03-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0007_item_ingredientes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
                ("disponivel", models.BooleanField(default=True)),
            ],
        ),
    ]
