# Generated by Django 4.1.7 on 2023-03-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0008_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuCategoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name="menu",
            name="categoria",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.menucategoria",
            ),
        ),
    ]
