# Generated by Django 4.1.7 on 2023-03-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0009_menucategoria_menu_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="categoria",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.menucategoria",
            ),
        ),
    ]
