# Generated by Django 4.1.7 on 2023-03-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0014_alter_item_ingredientes_alter_menu_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="ingredientes",
            field=models.ManyToManyField(blank=True, to="menu.ingredientes"),
        ),
    ]
