# Generated by Django 4.1.7 on 2023-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0015_alter_item_ingredientes"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(default=None, max_length=100)),
                ("imagem", models.ImageField(upload_to="menu_image")),
            ],
        ),
    ]
