# Generated by Django 4.1.7 on 2023-03-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0017_menu_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredientes",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="itemmedia",
            name="title",
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="menucategoria",
            name="nome",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="menumedia",
            name="nome",
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
