# Generated by Django 4.1.7 on 2023-03-29 14:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0018_alter_ingredientes_nome_alter_item_nome_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="item_media_id",
            new_name="media",
        ),
    ]
