# Generated by Django 4.1.7 on 2023-04-01 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0020_alter_item_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="media",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="menu.itemmedia",
            ),
        ),
    ]
